import Head from "next/head";
import Layout from "../components/Layout";
import Link from "next/link";
import Image from "next/image";
import profilePic from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from "../components/AnimatedText";
import Statistics from "../components/Statistics";
import Skills from "../components/Skills";
import { LinkArrow } from "../components/Icons";
export default function Home() {
  return (
    <>
      <Head>
        <title>React Website!</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout className="pt-0">
          <div className="flex flex-col md:flex-row items-center justify-between w-full">
            <div className="w-full sm:w-1/2 md:w-2/3">
              <Image src={profilePic} alt="Liam" className="w-full h-auto" priority />
            </div>
            <div className="w-full md:w-1/3: flex flex-col items-center self-center">
              <AnimatedText
                text="Hi, my name is Liam and I'm a data engineer."
                className="!text-3xl !text-left"
              />
              <p className="my-4 text-base font-medium hidden sm:block">
                <b>
                  This website is only for educational purposes. Some of the data may not be
                  factual.&nbsp;&nbsp;
                </b>
                I am a skilled technical professional with understanding of data architecture and
                infrastructure. My expertise lies in designing, building, maintaining, and
                optimizing large-scale data processing systems that enable organizations to collect,
                store, and analyze massive amounts of data.
              </p>

              <div className="flex items-center self-start mt-2">
                <Link
                  href="/resume_liam_chen.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-4 rounded-lg text-lg font-semibold
                   hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark"
                  download={true}
                >
                  Resume
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    strokeWidth={1.5}
                    stroke="currentColor"
                    className="w-6 h-6 ml-2"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M18.375 12.739l-7.693 7.693a4.5 4.5 0 01-6.364-6.364l10.94-10.94A3 3 0 1119.5 7.372L8.552 18.32m.009-.01l-.01.01m5.699-9.941l-7.81 7.81a1.5 1.5 0 002.112 2.13"
                    />
                  </svg>
                </Link>
                <Link
                  href="mailto:lichen.unsw@gmail.com"
                  target={"_blank"}
                  className="ml-4 text-lg font-medium text-dard underline"
                >
                  Contact me
                </Link>
              </div>
            </div>
          </div>
          <Statistics />
          <Skills />
        </Layout>
      </main>
    </>
  );
}
